name: Git CICD Heroku
on: [push]
jobs:
  build:
    environment:
      name: testing
    env:
      DOC_ID: ${{secrets.DOC_ID}}
      TYPE: ${{secrets.TYPE}}
      PROJECT_ID: ${{secrets.PROJECT_ID}}
      PRIVATE_KEY_ID: ${{secrets.PRIVATE_KEY_ID}}
      PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
      CLIENT_EMAIL: ${{secrets.CLIENT_EMAIL}}
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      AUTH_URI: ${{secrets.AUTH_URI}}
      TOKEN_URI: ${{secrets.TOKEN_URI}}
      AUTH_PROVIDER_X509_CERT_URL: ${{secrets.AUTH_PROVIDER_X509_CERT_URL}}
      CLIENT_X509_CERT_URL: ${{secrets.CLIENT_X509_CERT_URL}}
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: run pytest
        run: |
          pip install pytest
          pytest
